changing the workflow

diff --git a/.github/workflows/missing-redirects-check.yml b/.github/workflows/missing-redirects-check.yml
--- a/.github/workflows/missing-redirects-check.yml
+++ b/.github/workflows/missing-redirects-check.yml
@@ -17,15 +17,7 @@ jobs:
             frontmatter=$(cat $file | grep -Po 'redirect_from: *\K.*')
             relative_path="${file%.md}.md"
             if ! [[ $frontmatter =~ $relative_path ]]; then
-              echo "Error: Missing redirect for $relative_path" >> missing-redirects.txt
+              echo "Error: Missing redirect for $relative_path"
+              exit 1
             fi
           done
-
-      - name: Fail if missing redirects are found
-        if: ${{ always() }}
-        run: |
-          if [ -s missing-redirects.txt ]; then
-            echo "Workflow failed due to missing redirects"
-            cat missing-redirects.txt
-            exit 1
-          fi
